# Changes here will be overwritten by Copier
_commit: 4.0.1
_src_path: https://github.com/DiamondLightSource/python-copier-template
author_email: callum.forrester@diamond.ac.uk
author_name: Callum Forrester
component_lifecycle: production
component_owner: group:default/data-acquisition
component_type: service
description: Lightweight bluesky-as-a-service wrapper application. Also usable as
    a library.
distribution_name: blueapi
docker: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: blueapi
pypi: true
repo_name: blueapi
strict_typing: false
type_checker: pyright
