apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blueapi
  title: Athena BlueAPI
  description: Lightweight wrapper service around Bluesky Run Engine
  annotations:
    github.com/project-slug: DiamondLightSource/blueapi
    diamond.ac.uk/viewdocs-url: https://diamondlightsource.github.io/blueapi
spec:
  type: service
  lifecycle: production
  owner: user:vid18871 # TODO: owner: DAQ-Core
  #  system: Athena  # TODO: Define Athena system: presumably same location as DAQ-Core/DAQ?
  providesApis:
    - blueapiControl
    - blueapiEvents
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: blueapiControl
  title: Athena BlueAPI Control
  description: REST API for getting plans/devices from the worker (and running tasks)
  annotations:
    github.com/project-slug: DiamondLightSource/blueapi
spec:
  type: openapi
  lifecycle: production
  owner: user:vid18871
  definition:
    $text: ./docs/user/reference/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: blueapiEvents
  title: Athena BlueAPI Events
  description: Event topics which can be listened to over a message bus
  annotations:
    github.com/project-slug: DiamondLightSource/blueapi
spec:
  type: asyncapi
  lifecycle: production
  owner: user:vid18871
  definition:
    $text: ./docs/user/reference/asyncapi.yaml
