apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bluesky-worker
  title: bluesky-worker
  description: Lightweight wrapper around bluesky services
  annotations:
    github.com/project-slug: DiamondLightSouce/blueapi
spec:
  type: service
  lifecycle: production
  owner: user:vid18871 # TODO: owner: DAQ-Core
  #  system: Athena  # TODO: Define Athena system: presumably same location as DAQ-Core/DAQ?
  providesApis:
    - message-topics
    - restapi
    - blueskydocument-to-scanmessage
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: restapi
  title: restapi
  description: REST API for getting plans/devices from the worker (and running tasks)
spec:
  type: openapi
  lifecycle: production
  owner: user:vid18871
  definition:
    $text: ./docs/user/reference/openapi.json
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: message-topics
  title: message-topics
  description: Message topics which can be listened to over an activeMQ message bus
spec:
  type: asyncapi
  lifecycle: production
  owner: user:vid18871
  definition:
    $text: ./docs/user/reference/asyncapi.yaml
