apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blueapi
  title: BlueAPI Service
  description: The BlueAPI service for handling API requests.
  annotations:
    github.com/project-slug: your-org/blueapi
spec:
  type: service
  lifecycle: production
  owner: group:data-acquisition
  system: athena

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bluecli
  title: BlueCLI Service
  description: The BlueCLI service for command line operations.
  annotations:
    github.com/project-slug: your-org/bluecli
spec:
  type: service
  lifecycle: production
  owner: group:data-acquisition
  system: athena

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bluecommon
  title: BlueCommon Service
  description: The BlueCommon service for shared utilities.
  annotations:
    github.com/project-slug: your-org/bluecommon
spec:
  type: library
  lifecycle: production
  owner: group:data-acquisition
  system: athena

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blueworker
  title: BlueWorker Service
  description: The BlueWorker service for background processing.
  annotations:
    github.com/project-slug: your-org/blueworker
spec:
  type: service
  lifecycle: production
  owner: group:data-acquisition
  system: athena

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: common
  title: Common Service
  description: The Common service for common functionalities.
  annotations:
    github.com/project-slug: your-org/common
spec:
  type: library
  lifecycle: production
  owner: group:data-acquisition
  system: athena

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: generated
  title: Generated Service
  description: The Generated service for autogenerated components.
  annotations:
    github.com/project-slug: your-org/generated
spec:
  type: library
  lifecycle: production
  owner: group:data-acquisition
  system: athena

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: proto
  title: Proto Service
  description: The Proto service for protocol definitions.
  annotations:
    github.com/project-slug: your-org/proto
spec:
  type: library
  lifecycle: production
  owner: group:data-acquisition
  system: athena
