[project]
name = "blueapi-common"
version = "0.1.0"
description = "Common API to blueapi"
readme = "README.md"
authors = [
    { name = "Peter Holloway", email = "holloway.p.r@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "blueapi-common.inject"
]
