services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - ./rabbitmq_setup/enabled_plugins:/etc/rabbitmq/enabled_plugins
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    ports:
      - 8080:8080
    environment:
      JSON_CONFIG: '{ "interactiveLogin": false, "httpServer": "MockWebServerWrapper", "tokenCallbacks": [ { "issuerId": "auth", "tokenExpiry": 120, "requestMappings": [] } ] }'
