{{- /*
  It is recommended to instead mount this as a SealedSecret, for instructions see the readme.
  This template defines the secret that is mounted to the Envoy sidecar to enable the oauth flow. It takes 1 required
  argument and has 2 optional arguments:
    Required Arguments:
      Secret: the client secret for the client of the oauth flow
    Optional Arguments:
      Name: a unique (among Secrets in the namespace) String
        default: authn-secret
      Hmac: the hmac string used to encrypt cookies
        default: a random 32 digit string
  */}}
{{- define "authn-template.secret.tpl" -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Name | default "authn-secret" }}
stringData:
  secret.yaml: |-
    resources:
      - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
        name: token
        generic_secret:
          secret:
            inline_string: {{ required "The client secret must be provided!" .Secret }}
      - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
        name: hmac
        generic_secret:
          secret:
            inline_string: {{ .Hmac | default (randAlphaNum 32) }}

---

{{ end -}}