image:
  repository: ghcr.io/dan-fernandes/blueapi
  # tag: "1.12.13"
debug:
  enabled: true
hostNetwork: false
ingress:
  enabled: false
  hosts:
    - host: p48-blueapi.diamond.ac.uk
      paths:
        - path: /
          pathType: Prefix

nodeSelector:
  beamline: p48

tolerations:
  - key: beamline
    operator: Equal
    value: p48
    effect: NoSchedule
  - key: nodetype
    operator: Equal
    value: training-rig
    effect: NoSchedule

extraEnvVars:
  - name: BEAMLINE
    value: p48
  - name: INSTRUMENT
    value: p48
  - name: EPICS_PVA_NAME_SERVERS
    value: p48-epics-gateways:9075
  - name: EPICS_CA_NAME_SERVERS
    value: p48-epics-gateways:9064
  - name: EPICS_PVA_AUTO_ADDR_LIST
    value: "NO"
  - name: EPICS_CA_AUTO_ADDR_LIST
    value: "NO"

  - name: TILED_WRITER_SECRET
    valueFrom:
      secretKeyRef:
        name: blueapi-secret
        key: tiled-writer-secret

worker:
  env:
    metadata:
      instrument: p48
    sources:
      - kind: deviceManager
        module: dodal.beamlines.training_rig
      - kind: planFunctions
        module: dodal.plans
    events:
      broadcast_status_events: false
  stomp:
    auth:
      username: guest
      password: guest
    url: tcp://p48-rabbitmq-daq.diamond.ac.uk:61613
    enabled: true
  logging:
    level: "INFO"
    graylog:
      enabled: true

  oidc:
    well_known_url: "https://identity.diamond.ac.uk/realms/dls/.well-known/openid-configuration"
    client_id: "blueapiCli"
    client_audience: "account"
    logout_redirect_endpoint: "oauth2/sign_out"

  numtracker:
    url: https://numtracker-staging.diamond.ac.uk/graphql

  tiled:
    enabled: true
    url: "https://tiled.diamond.ac.uk/api/v1/"
    authentication:
      client_id: "p48TiledWriter"
      client_secret: ${TILED_WRITER_SECRET}

  scratch:
    root: /workspaces
    repositories:
      - name: dodal
        remote_url: https://github.com/DiamondLightSource/dodal.git
      - name: htss-rig-bluesky
        remote_url: https://github.com/DiamondLightSource/htss-rig-bluesky.git
        target_revision: update-copier-template
      # - name: ophyd-async
      #   remote_url: https://github.com/bluesky/ophyd-async.git

initContainer:
  enabled: true
  persistentVolume:
    enabled: true
    size: "2Gi"
