env:
  sources:
    - kind: dodal
      module: dodal.beamlines.p38
    - kind: planFunctions
      module: dls_bluesky_core.plans
    - kind: planFunctions
      module: dls_bluesky_core.stubs
  data_writing:
    visit_directory: /dls/p38/data/2023/cm33874-1
    group_name: BL38P
