env:
  sources:
    - kind: deviceFunctions
      module: blueapi.startup.example
    - kind: planFunctions
      module: blueapi.plans
stomp:
  host: localhost
  port: 61613
logging:
  level: "INFO"
