env:
  sources:
    - kind: deviceFunctions
      module: blueapi.startup.example_devices
    - kind: planFunctions
      module: blueapi.startup.example_plans
    - kind: planFunctions
      module: dls_bluesky_core.plans
    - kind: planFunctions
      module: dls_bluesky_core.stubs
  scratch:
    path: /blueapi-plugins/scratch
    auto_make_directory: true
stomp:
  host: localhost
  port: 61613
logging:
  level: "INFO"
