# coding: utf-8

"""
    BlueAPI Control

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr
from openapi_client.models.worker_state import WorkerState

class StateChangeRequest(BaseModel):
    """
    Request to change the state of the worker.  # noqa: E501
    """
    defer: Optional[StrictBool] = Field(default=False, description="Should worker defer Pausing until the next checkpoint")
    new_state: WorkerState = Field(...)
    reason: Optional[StrictStr] = Field(default=None, description="The reason for the current run to be aborted")
    __properties = ["defer", "new_state", "reason"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StateChangeRequest:
        """Create an instance of StateChangeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StateChangeRequest:
        """Create an instance of StateChangeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StateChangeRequest.parse_obj(obj)

        _obj = StateChangeRequest.parse_obj({
            "defer": obj.get("defer") if obj.get("defer") is not None else False,
            "new_state": obj.get("new_state"),
            "reason": obj.get("reason")
        })
        return _obj


