# coding: utf-8

"""
    BlueAPI Control

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg



class WorkerState( Enum):
    """
    The state of the Worker.
    """

    """
    allowed enum values
    """
    IDLE = 'IDLE'
    RUNNING = 'RUNNING'
    PAUSING = 'PAUSING'
    PAUSED = 'PAUSED'
    HALTING = 'HALTING'
    STOPPING = 'STOPPING'
    ABORTING = 'ABORTING'
    SUSPENDING = 'SUSPENDING'
    PANICKED = 'PANICKED'
    UNKNOWN = 'UNKNOWN'

    @classmethod
    def from_json(cls, json_str: str) -> WorkerState:
        """Create an instance of WorkerState from a JSON string"""
        return WorkerState(json.loads(json_str))


