name: Setup UV
description: Setup UV and install the project
inputs:
  python-version:
    description: Python version to install, default is from Dockerfile
    default: "dev"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        # Need this to get version number from last tag
        fetch-depth: 0

    - name: Get version of python
      run: |
        PYTHON_VERSION="${{ inputs.python-version }}"
        if [ $PYTHON_VERSION == "dev" ]; then
          # python version from Dockerfile, removing potential pinned sha
          PYTHON_VERSION=$(sed -Ene "s/ARG PYTHON_VERSION=([0-9\.]+).*/\1/p" Dockerfile)
        fi
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"
      shell: bash

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        enable-cache: true

    - name: Install project
      run: uv sync --locked --all-extras --dev

    - name: List dependency tree
      run: uv export --format requirements.txt --no-hashes
