apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blueapi.fullname" . }}-config
data:
  config.yaml: |-
    {{- toYaml .Values.worker | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blueapi.fullname" . }}-otel-config
data:
{{- if .Values.tracing.otlp.enabled | default false }}
  OTLP_EXPORT_ENABLED: "true"
  OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: {{ .Values.tracing.otlp.protocol | default "http/protobuf" }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ required "OTLP export enabled but server address not set" .Values.tracing.otlp.server.host }}:{{ .Values.tracing.otlp.server.port | default 4318 }}
{{ end }}
