{{- if .Values.initContainer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blueapi.fullname" . }}-initconfig
data:
  initconfig.yaml: |-
    scratch:
      {{- toYaml .Values.worker.scratch | nindent 6 }}
{{- end }}
---
