apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blueapi.fullname" . }}-initconfig
data:
  initconfig.yaml: |-
    {{- if .Values.initContainer.enabled }}
    scratch:
      {{- toYaml .Values.initContainer.scratch | nindent 4 }}
    {{- end }}
---
