{{/* An example secret for mounting a secret with stomp auth information. For production use a SealedSecret */}}
{{ with false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blueapi.fullname" . }}
stringData:
  secret.yaml:
    stomp:
      auth:
        passcode: foo
{{- end }}
