components:
  schemas:
    DeviceModel:
      additionalProperties: false
      description: Representation of a device
      properties:
        name:
          description: Name of the device
          title: Name
          type: string
        protocols:
          description: Protocols that a device conforms to, indicating its capabilities
          items:
            type: string
          title: Protocols
          type: array
      required:
      - name
      - protocols
      title: DeviceModel
      type: object
    DeviceResponse:
      additionalProperties: false
      description: Response to a query for devices
      properties:
        devices:
          description: Devices available to use in plans
          items:
            $ref: '#/components/schemas/DeviceModel'
          title: Devices
          type: array
      required:
      - devices
      title: DeviceResponse
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    PlanModel:
      additionalProperties: false
      description: Representation of a plan
      properties:
        name:
          description: Name of the plan
          title: Name
          type: string
      required:
      - name
      title: PlanModel
      type: object
    PlanResponse:
      additionalProperties: false
      description: Response to a query for plans
      properties:
        plans:
          description: Plans available to use by a worker
          items:
            $ref: '#/components/schemas/PlanModel'
          title: Plans
          type: array
      required:
      - plans
      title: PlanResponse
      type: object
    RunPlan:
      additionalProperties: false
      description: Task that will run a plan
      properties:
        name:
          description: Name of plan to run
          title: Name
          type: string
        params:
          description: Values for parameters to plan, if any
          title: Params
          type: object
      required:
      - name
      title: RunPlan
      type: object
    TaskResponse:
      additionalProperties: false
      description: Acknowledgement that a task has started, includes its ID
      properties:
        taskId:
          description: Unique identifier for the task
          title: Taskid
          type: string
      required:
      - taskId
      title: TaskResponse
      type: object
    TrackableTask:
      additionalProperties: false
      description: A representation of a task that the worker recognizes
      properties:
        isComplete:
          default: false
          title: Iscomplete
          type: boolean
        isError:
          default: false
          title: Iserror
          type: boolean
        isPending:
          default: true
          title: Ispending
          type: boolean
        task:
          title: Task
        taskId:
          title: Taskid
          type: string
      required:
      - taskId
      title: TrackableTask
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
    WorkerState:
      description: The state of the Worker.
      enum:
      - IDLE
      - RUNNING
      - PAUSING
      - PAUSED
      - HALTING
      - STOPPING
      - ABORTING
      - SUSPENDING
      - PANICKED
      - UNKNOWN
      title: WorkerState
      type: string
    WorkerTask:
      additionalProperties: false
      description: Worker's active task ID, can be None
      properties:
        taskId:
          description: The ID of the current task, None if the worker is idle
          title: Taskid
          type: string
      title: WorkerTask
      type: object
info:
  title: BlueAPI Control
  version: 0.0.2
openapi: 3.0.2
paths:
  /devices:
    get:
      description: Retrieve information about all available devices.
      operationId: get_devices_devices_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceResponse'
          description: Successful Response
      summary: Get Devices
  /devices/{name}:
    get:
      description: Retrieve information about a devices by its (unique) name.
      operationId: get_device_by_name_devices__name__get
      parameters:
      - in: path
        name: name
        required: true
        schema:
          title: Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceModel'
          description: Successful Response
        '404':
          description: Not Found
          item: not found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Device By Name
  /plans:
    get:
      description: Retrieve information about all available plans.
      operationId: get_plans_plans_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanResponse'
          description: Successful Response
      summary: Get Plans
  /plans/{name}:
    get:
      description: Retrieve information about a plan by its (unique) name.
      operationId: get_plan_by_name_plans__name__get
      parameters:
      - in: path
        name: name
        required: true
        schema:
          title: Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanModel'
          description: Successful Response
        '404':
          description: Not Found
          item: not found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Plan By Name
  /tasks:
    post:
      description: Submit a task to the worker.
      operationId: submit_task_tasks_post
      requestBody:
        content:
          application/json:
            example:
              name: count
              params:
                detectors:
                - x
            schema:
              $ref: '#/components/schemas/RunPlan'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Submit Task
  /tasks/{task_id}:
    get:
      description: Retrieve a task
      operationId: get_task_tasks__task_id__get
      parameters:
      - in: path
        name: task_id
        required: true
        schema:
          title: Task Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackableTask'
          description: Successful Response
        '404':
          description: Not Found
          item: not found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Task
  /worker/state:
    get:
      description: Get the State of the Worker
      operationId: get_state_worker_state_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkerState'
          description: Successful Response
      summary: Get State
  /worker/task:
    get:
      operationId: get_active_task_worker_task_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkerTask'
          description: Successful Response
      summary: Get Active Task
    put:
      operationId: update_task_worker_task_put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkerTask'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkerTask'
          description: Successful Response
        '409':
          description: Conflict
          worker: already active
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Task
