on:
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install_requirements

      - name: Build sdist and wheel
        run: >
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) &&
          uv build --frozen

      - name: Upload sdist and wheel as artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: dist
          path: dist

      - name: Check for packaging errors
        run: uvx twine check --strict dist/*

      - name: Install produced wheel
        uses: ./.github/actions/install_requirements
        with:
          # TODO: figure out what's going on
          pip-install: dist/*.whl

      - name: Test module --version works using the installed wheel
        # If more than one module in src/ replace with module name to test
        run: python -m $(ls --hide='*.egg-info' src | head -1) --version
