on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Avoid git conflicts when tag and branch pushed at same time
        if: github.ref_type == 'tag'
        run: sleep 60

      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Install system packages
        run: sudo apt-get install graphviz

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build docs
        run: uv run --locked tox -e docs

      - name: Remove environment.pickle
        run: rm build/html/.doctrees/environment.pickle

      - name: Sanitize ref name for docs version
        run: echo "DOCS_VERSION=${GITHUB_REF_NAME//[^A-Za-z0-9._-]/_}" >> $GITHUB_ENV

      - name: Move to versioned directory
        run: mv build/html .github/pages/$DOCS_VERSION

      - name: Write switcher.json
        run: python .github/pages/make_switcher.py --add $DOCS_VERSION ${{ github.repository }} .github/pages/switcher.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5

  deploy:
    if: github.ref_type == 'tag'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

