on:
  workflow_call:

env:
  # https://github.com/pytest-dev/pytest/issues/2042
  PY_IGNORE_IMPORTMISMATCH: "1"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          # Need this to get version number from last tag
          fetch-depth: 0
          # Check out example services
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Cache Docker Compose Images
        id: cache-docker
        uses: seijikohara/docker-compose-cache-action@fe63c2c0dfe435a8852d9e9c361d8b378ad50c3a # v1.8.21
        with:
          skip-digest-verification: true
          compose-files: |
            tests/system_tests/compose.yaml
            example-services/compose.yaml
            example-services/services/bl01t-ea-test-01/compose.yml
            example-services/services/bl01t-di-cam-01/compose.yml
            example-services/services/bl01t-mo-sim-01/compose.yml
            example-services/services/gateway/compose.yml
            example-services/services/pvagw/compose.yml
            example-services/services/epics-opis/compose.yml
            example-services/services/phoebus/compose.yml


      - name: Display Cache Info
        run: |
          echo "Cache hit for all images: ${{ steps.cache-docker.outputs.cache-hit }}"

          # Parse the JSON output to display image information
          IMAGE_LIST='${{ steps.cache-docker.outputs.image-list }}'

          if [[ -n "$IMAGE_LIST" ]]; then
            echo "Images processed:"
            echo "$IMAGE_LIST" | jq -r '.[] | "- \(.name) [\(.status)]: \(.size) bytes processed in \(.processingTimeMs)ms"'
          else
            echo "No images processed"
          fi
              
      # - name: Set up Docker Compose
      #   uses: docker/setup-compose-action@v2
      #   with:
      #     version: v5.4.0
      
      - name: Run all example services
        run: docker compose -f tests/system_tests/compose.yaml up -d

      - name: Start Blueapi Server
        env:
          EPICS_CA_NAME_SERVERS: 127.0.0.1:9064
          EPICS_PVA_NAME_SERVERS: 127.0.0.1:9075
        run: uv run blueapi -c ${{ github.workspace }}/tests/system_tests/config.yaml serve &

      - name: Run tests
        run: uv run --locked tox -e system-test

      - name: Stop services
        if: always()
        run: docker compose -f tests/system_tests/compose.yaml down
