# Validates the AsyncAPI definition

name: AsyncAPI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: check asyncapi.yaml file
        uses: asyncapi/cli@63df7607f902aba80e2ef4d88a5605821f49ec58 # v6.2.0
        with:
          command: validate
          filepath: "./docs/reference/asyncapi.yaml"
