# Validates the AsyncAPI definition

name: AsyncAPI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: check asyncapi.yaml file
        uses: asyncapi/cli@fb73ff3a429c1bc6a14c1b89f12601288677b9fa # v6.0.2
        with:
          command: validate
          filepath: "./docs/reference/asyncapi.yaml"
