name: Backstage

on:
  push:
  pull_request:

jobs:
  validate:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: check catalog-info.yaml file
        uses: RoadieHQ/backstage-entity-validator@v0.3.11
        with:
          path: "./catalog-info.yaml"
