name: Backstage

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: check catalog-info.yaml file
        uses: RoadieHQ/backstage-entity-validator@d39db2335a810aed3175c5ba9b86b89b7c7286c1 # v0.5.0
        with:
          path: "./catalog-info.yaml"
