name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:

  lint:
    uses: ./.github/workflows/_tox.yml
    with:
      tox: pre-commit,type-checking

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0
      - name: Setup project
        uses: ./.github/actions/install_requirements
        with:
          python-version: ${{ matrix.python-version }}

      - name: Unit tests
        run: uv run --frozen tox -e tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          name: ${{ matrix.python-version }}/ubuntu-latest
          files: cov.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  system-test:
    uses: ./.github/workflows/_system_test.yml

  container:
    needs: [test, system-test]
    if: always()
    uses: ./.github/workflows/_container.yml
    with:
      publish: ${{ needs.test.result == 'success' }}
    permissions:
      contents: read
      packages: write

  debug_container:
    needs: [container, test]
    uses: ./.github/workflows/_debug_container.yml
    with:
      publish: ${{ needs.test.result == 'success' }}
    permissions:
      contents: read
      packages: write

  docs:
    uses: ./.github/workflows/_docs.yml


  dist:
    uses: ./.github/workflows/_dist.yml

  pypi:
    needs: [dist, test]
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/_pypi.yml
    permissions:
      id-token: write

  release:
    needs: [dist, test, docs, container]
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
