name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:

  lint:
    uses: ./.github/workflows/_tox.yml
    with:
      tox: pre-commit,type-checking

  uv_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Setup project
        uses: ./.github/actions/install_requirements
        with:
          python-version: ${{ matrix.python-version }}

      - name: Unit tests
        run: uv run tox -e tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          name: ${{ matrix.python-version }}/ubuntu-latest
          files: cov.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  system-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup project
        uses: ./.github/actions/install_requirements
        with:
          python-version: 3.12

      - name: Start RabbitMQ
        uses: namoshek/rabbitmq-github-action@d1d4455f4a8f72db66111c24cb0dc5654047a975 # v1
        with:
          ports: "61613:61613"
          plugins: rabbitmq_stomp

      - name: Start Blueapi Server
        run: uv run blueapi -c ${{ github.workspace }}/tests/unit_tests/example_yaml/valid_stomp_config.yaml serve &

      - name: Run tests
        run: uv run tox -e system-test

  container:
    needs: test
    if: always()
    uses: ./.github/workflows/_container.yml
    with:
      publish: ${{ needs.test.result == 'success' }}
    permissions:
      contents: read
      packages: write

  debug_container:
    needs: [container, test]
    uses: ./.github/workflows/_debug_container.yml
    with:
      publish: ${{ needs.test.result == 'success' }}
    permissions:
      contents: read
      packages: write

  docs:
    uses: ./.github/workflows/_docs.yml


  dist:
    uses: ./.github/workflows/_dist.yml

  pypi:
    needs: [dist, test]
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/_pypi.yml
    permissions:
      id-token: write

  release:
    needs: [dist, test, docs]
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
