name: Helm CI

on:
  push:
    tags:
      - "*"

env:
  GCR_IMAGE: ghcr.io/diamondlightsource/blueapi
  HELM_VERSION: 3.10.3

jobs:
  build:
    name: publish gcr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install helm
        uses: Azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: login to acr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@70b2cdc6480c1a8b86edf1777157f8f437de2166
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
      - name: package chart and push it
        run: |
          sed -i "$ a appVersion: ${GITHUB_REF##*/}" helm/blueapi/Chart.yaml
          helm dependencies update helm/blueapi
          helm package helm/blueapi --version ${GITHUB_REF##*/} -d /tmp/
          helm push /tmp/blueapi-${GITHUB_REF##*/}.tgz oci://ghcr.io/diamondlightsource/charts
