# Validates the AsyncAPI definition

name: asyncapi_validate

on:
  push:
  pull_request:

jobs:
  validate:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: asyncapi-validate
        uses: WaleedAshraf/asyncapi-github-action@v0.0.10
        with:
          filepath: "./docs/user/reference/asyncapi.yaml"
